services:
  db:
    image: postgres:13
    container_name: db
    env_file: ".env"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    command: > 
      sh -c "python manage.py makemigrations && python manage.py migrate && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/credit_approval_system_db"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge