# Generated by Django 5.1.3 on 2024-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_monthly_repayment_loan_monthly_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
