# Generated by Django 5.1.3 on 2024-11-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
