# Generated by Django 5.1.3 on 2024-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_emis_paid_on_time_alter_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
